name: Deploy Java App to Azure
on:
 push:
 branches:
 - main # Runs on every push to main branch
jobs:
 build-and-deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout Repository
 uses: actions/checkout@v3
 - name: Set up Java
 uses: actions/setup-java@v3
 with:
 distribution: 'temurin'
 java-version: '17'
 - name: Build Java Application
 run: mvn clean package
 - name: Deploy to Azure App Service
 uses: azure/webapps-deploy@v2
 with:
 app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
 publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
 package: target/*.jar
